import Foundation
import SwiftSyntax
import SwiftParser

enum RunMode {
    case analyze
    case context
    case findDependents(String)
    case fullSummary
    case focus(String)
    case directScan(projectPath: String, outputPath: String)
}

func run() throws {
    let args = Array(CommandLine.arguments.dropFirst())
    guard !args.isEmpty else { throw PrismError.noInputPaths }

    if let mode = detectDirectScanMode(args) {
        try runDirectScan(mode)
        return
    }

    try runFlagMode(args)
}

func detectDirectScanMode(_ args: [String]) -> RunMode? {
    guard args.count == 2 else { return nil }
    let first = args[0]
    let second = args[1]
    guard !first.hasPrefix("-") && !second.hasPrefix("-") else { return nil }
    guard second.hasSuffix(".json") else { return nil }
    return .directScan(projectPath: first, outputPath: second)
}

func runDirectScan(_ mode: RunMode) throws {
    guard case .directScan(let projectPath, let outputPath) = mode else { return }

    let fm = FileManager.default
    let resolvedPath = (projectPath as NSString).standardizingPath
    var isDir: ObjCBool = false

    guard fm.fileExists(atPath: resolvedPath, isDirectory: &isDir), isDir.boolValue else {
        throw PrismError.directoryInaccessible(resolvedPath)
    }

    guard fm.isReadableFile(atPath: resolvedPath) else {
        throw PrismError.directoryInaccessible(resolvedPath)
    }

    emitProgress(phase: "scanning", processed: 0, total: 0)

    let swiftFiles = discoverSwiftFiles(in: resolvedPath)
    guard !swiftFiles.isEmpty else {
        throw PrismError.noSwiftFilesFound(resolvedPath)
    }

    let (allSymbols, fileSources) = scanFiles(swiftFiles)

    let resources = scanResources(workspaceRoot: resolvedPath)

    emitProgress(phase: "resolving", processed: 0, total: 1)

    let resolver = DependencyResolver(
        fileSources: fileSources,
        symbols: allSymbols,
        resources: resources,
        targets: [],
        macros: [],
        publicOnlyTargets: []
    )
    let result = resolver.resolve()

    let flatEntries = convertToFlatMap(result)

    let json = try safeEncodeToJSON(flatEntries, label: "FlatMapEntry")

    do {
        let outputDir = (outputPath as NSString).deletingLastPathComponent
        if !outputDir.isEmpty && !fm.fileExists(atPath: outputDir) {
            try fm.createDirectory(atPath: outputDir, withIntermediateDirectories: true)
        }
        try json.write(toFile: outputPath, atomically: true, encoding: .utf8)
    } catch {
        throw PrismError.outputWriteFailed("\(outputPath): \(error.localizedDescription)")
    }

    emitProgress(phase: "complete", processed: 1, total: 1)
    fputs("{\"_info\":\"Written \(flatEntries.count) entries to \(outputPath)\"}\n", stderr)
}

func convertToFlatMap(_ result: AnalysisResult) -> [FlatMapEntry] {
    var outgoing: [String: [String]] = [:]
    for link in result.links {
        outgoing[link.sourceId, default: []].append(link.targetId)
    }

    return result.nodes.map { node in
        FlatMapEntry(
            id: node.id,
            name: node.name,
            type: node.flavor.rawValue,
            location: FlatLocation(
                file: node.location.file,
                line: node.location.line,
                col: node.location.column
            ),
            connections: (outgoing[node.id] ?? []).sorted()
        )
    }
}

func discoverSwiftFiles(in directory: String) -> [String] {
    let fm = FileManager.default
    let skipDirs: Set<String> = [
        ".build", "Build", "DerivedData", "Pods", ".swiftpm",
        "node_modules", ".git", "Carthage", "SourcePackages",
        "checkouts", "artifacts", ".index-build",
    ]
    let skipSuffixes = ["_generated.swift", ".pb.swift", ".grpc.swift"]

    guard let enumerator = fm.enumerator(
        at: URL(fileURLWithPath: directory),
        includingPropertiesForKeys: [.isDirectoryKey, .isRegularFileKey],
        options: [.skipsHiddenFiles]
    ) else { return [] }

    var files: [String] = []
    while let url = enumerator.nextObject() as? URL {
        let name = url.lastPathComponent
        if skipDirs.contains(name) {
            enumerator.skipDescendants()
            continue
        }
        guard url.pathExtension == "swift" else { continue }
        let shouldSkip = skipSuffixes.contains { name.hasSuffix($0) }
        if shouldSkip {
            emitWarning("Skipping autogenerated file: \(url.path)")
            continue
        }
        files.append(url.path)
    }
    return files.sorted()
}

func runFlagMode(_ args: [String]) throws {
    var workspaceRoot: String?
    var filePaths: [String] = []
    var mode: RunMode = .analyze
    var outputPath: String?
    var scanTargets = false
    var publicOnlyExternal = false
    var summaryOnly = false
    var membersOfId: String?
    var collapseModulesFlag = false

    var i = 0
    while i < args.count {
        switch args[i] {
        case "--workspace" where i + 1 < args.count:
            workspaceRoot = args[i + 1]; i += 2
        case "--context":
            mode = .context; i += 1
        case "--find-dependents-of" where i + 1 < args.count:
            mode = .findDependents(args[i + 1]); i += 2
        case "--output" where i + 1 < args.count:
            outputPath = args[i + 1]; i += 2
        case "--scan-targets":
            scanTargets = true; i += 1
        case "--public-only-external":
            publicOnlyExternal = true; i += 1
        case "--summary-only":
            summaryOnly = true; i += 1
        case "--members-of" where i + 1 < args.count:
            membersOfId = args[i + 1]; i += 2
        case "--collapse-modules":
            collapseModulesFlag = true; i += 1
        case "--full-summary":
            mode = .fullSummary; i += 1
        case "--focus" where i + 1 < args.count:
            mode = .focus(args[i + 1]); i += 2
        default:
            filePaths.append(args[i]); i += 1
        }
    }

    if filePaths.isEmpty && workspaceRoot == nil {
        throw PrismError.noInputPaths
    }

    var targets: [ParsedTarget] = []
    var publicOnlyTargets: Set<String> = []

    if scanTargets || (filePaths.isEmpty && workspaceRoot != nil) {
        if let root = workspaceRoot {
            emitProgress(phase: "targets", processed: 0, total: 1)
            let targetResolver = TargetResolver(workspaceRoot: root)
            targets = targetResolver.resolve()
            emitProgress(phase: "targets", processed: 1, total: 1)

            if filePaths.isEmpty {
                filePaths = targets.flatMap(\.sourcePaths)
            }

            if publicOnlyExternal {
                for target in targets {
                    if targetResolver.shouldIndexPublicOnly(targetName: target.name, targets: targets) {
                        publicOnlyTargets.insert(target.name)
                    }
                }
            }
        }
    }

    var (allSymbols, fileSources) = scanFiles(filePaths)

    if !targets.isEmpty, let root = workspaceRoot {
        let targetResolver = TargetResolver(workspaceRoot: root)
        for idx in allSymbols.indices {
            allSymbols[idx].targetName = targetResolver.mapFileToTarget(allSymbols[idx].location.file, targets: targets)
        }
    }

    let resources = scanResources(workspaceRoot: workspaceRoot)

    emitProgress(phase: "macros", processed: 0, total: 1)
    var allMacros: [MacroInfo] = []
    for (filePath, tree) in fileSources {
        let macroCollector = MacroCollector(filePath: filePath)
        macroCollector.walk(tree)
        var collected = macroCollector.macros
        if !targets.isEmpty, let root = workspaceRoot {
            let targetResolver = TargetResolver(workspaceRoot: root)
            for idx in collected.indices {
                collected[idx].targetName = targetResolver.mapFileToTarget(filePath, targets: targets)
            }
        }
        allMacros.append(contentsOf: collected)
    }
    emitProgress(phase: "macros", processed: 1, total: 1)

    emitProgress(phase: "resolving", processed: 0, total: 1)
    let resolver = DependencyResolver(
        fileSources: fileSources,
        symbols: allSymbols,
        resources: resources,
        targets: targets,
        macros: allMacros,
        publicOnlyTargets: publicOnlyTargets
    )
    let fullResult = resolver.resolve()

    var result: AnalysisResult
    if let membersOfId {
        result = extractMembers(of: membersOfId, from: fullResult)
    } else if summaryOnly {
        result = extractSummary(from: fullResult)
    } else {
        result = fullResult
    }

    if let root = workspaceRoot {
        result = AnalysisResult(
            projectRoot: root,
            nodes: result.nodes,
            links: result.links,
            resources: result.resources,
            targets: result.targets,
            macros: result.macros,
            moduleNodes: result.moduleNodes
        )
    }

    if collapseModulesFlag && !targets.isEmpty {
        result = collapseModules(result: result, targets: targets)
    }

    switch mode {
    case .analyze:
        let json = try safeEncodeToJSON(result, label: "AnalysisResult")
        writeOutput(json, to: outputPath)

    case .context:
        let signaturesByFile = collectSignatures(filePaths: filePaths, fileSources: fileSources)
        let generator = ContextGenerator(analysisResult: result, signaturesByFile: signaturesByFile)
        let context = generator.generate()
        let json = try safeEncodeToJSON(context, label: "PrismContext")
        writeOutput(json, to: outputPath)

    case .findDependents(let targetId):
        let signaturesByFile = collectSignatures(filePaths: filePaths, fileSources: fileSources)
        let generator = ContextGenerator(analysisResult: result, signaturesByFile: signaturesByFile)
        let dependents = generator.generateDependentsOf(targetId)
        let json = try safeEncodeToJSON(dependents, label: "Dependents")
        writeOutput(json, to: outputPath)

    case .fullSummary:
        let summary = generateFullSummary(result: fullResult)
        let json = try safeEncodeToJSON(summary, label: "FullSummary")
        writeOutput(json, to: outputPath)

    case .focus(let rootId):
        let focus = generateFocusAnalysis(rootId: rootId, result: fullResult)
        let json = try safeEncodeToJSON(focus, label: "FocusAnalysis")
        writeOutput(json, to: outputPath)

    case .directScan:
        break
    }

    emitProgress(phase: "complete", processed: 1, total: 1)
}

func generateFocusAnalysis(rootId: String, result: AnalysisResult) -> FocusAnalysis {
    let nodeById = Dictionary(result.nodes.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
    let topLevelFlavors: Set<String> = ["struct", "class", "enum", "actor", "protocol"]

    var outgoing: [String: [String]] = [:]
    for link in result.links {
        outgoing[link.sourceId, default: []].append(link.targetId)
    }

    var required: [String: Int] = [:]
    var queue: [(id: String, depth: Int)] = [(rootId, 0)]
    required[rootId] = 0

    if let rootNode = nodeById[rootId], topLevelFlavors.contains(rootNode.flavor.rawValue) {
        for child in result.nodes where child.parent == rootId {
            if required[child.id] == nil {
                required[child.id] = 1
                queue.append((child.id, 1))
            }
        }
    }

    while !queue.isEmpty {
        let (currentId, depth) = queue.removeFirst()
        let deps = outgoing[currentId] ?? []
        for dep in deps {
            if required[dep] == nil {
                required[dep] = depth + 1
                queue.append((dep, depth + 1))

                if let depNode = nodeById[dep], topLevelFlavors.contains(depNode.flavor.rawValue) {
                    for child in result.nodes where child.parent == dep {
                        if required[child.id] == nil {
                            required[child.id] = depth + 2
                            queue.append((child.id, depth + 2))
                        }
                    }
                }
            }
        }
    }

    let requiredSymbols = required.sorted { $0.value < $1.value }.compactMap { (id, depth) -> FocusSymbol? in
        guard let node = nodeById[id] else { return nil }
        let isStub = depth > 3 && (node.flavor == .function || node.flavor == .initializer)
        return FocusSymbol(
            id: id,
            name: node.name,
            flavor: node.flavor.rawValue,
            depth: depth,
            sourceFile: node.sourceFile,
            isStub: isStub
        )
    }

    let requiredFiles = Array(Set(requiredSymbols.map(\.sourceFile))).sorted()

    let allFiles = Array(Set(result.nodes.map(\.sourceFile))).sorted()
    let redundant = result.nodes.filter { required[$0.id] == nil }.map(\.id).sorted()

    var blastRadius: [String: [String]] = [:]
    for sym in requiredSymbols where sym.depth <= 2 {
        var affected: [String] = []
        for link in result.links where link.targetId == sym.id {
            if required[link.sourceId] != nil {
                affected.append(link.sourceId)
            }
        }
        if !affected.isEmpty {
            blastRadius[sym.id] = affected.sorted()
        }
    }

    let reqCount = requiredSymbols.count
    let totalCount = result.nodes.count
    let reqFiles = requiredFiles.count
    let totalFiles = allFiles.count
    let pct = totalCount > 0 ? Int(Double(reqCount) / Double(totalCount) * 100) : 0

    return FocusAnalysis(
        rootId: rootId,
        requiredSymbols: requiredSymbols,
        requiredFiles: requiredFiles,
        requiredFrameworks: [],
        redundantSymbols: redundant,
        unusedFrameworks: [],
        blastRadius: blastRadius,
        efficiency: FocusEfficiency(
            requiredSymbolCount: reqCount,
            totalSymbolCount: totalCount,
            requiredFileCount: reqFiles,
            totalFileCount: totalFiles,
            requiredFrameworkCount: 0,
            totalFrameworkCount: 0,
            summary: "You need \(pct)% of symbols (\(reqCount)/\(totalCount)) and \(reqFiles)/\(totalFiles) files to build \(rootId)."
        )
    )
}

func generateFullSummary(result: AnalysisResult) -> FullSummary {
    var outgoing: [String: Set<String>] = [:]
    var incoming: [String: Set<String>] = [:]

    for link in result.links {
        outgoing[link.sourceId, default: []].insert(link.targetId)
        incoming[link.targetId, default: []].insert(link.sourceId)
    }

    let allIds = Set(result.nodes.map(\.id))
    let topLevelFlavors: Set<String> = ["struct", "class", "enum", "actor", "protocol"]

    var symbols: [SymbolSummary] = []
    var deadCode: [DeadCodeEntry] = []
    var isolatedTypes = 0
    var writeOnlyCount = 0
    var initOnlyCount = 0

    for node in result.nodes {
        let inRefs = incoming[node.id] ?? []
        let outRefs = outgoing[node.id] ?? []
        let refCount = inRefs.count

        let isVisible = node.isInteresting || topLevelFlavors.contains(node.flavor.rawValue) || node.flavor == .function || node.flavor == .initializer

        symbols.append(SymbolSummary(
            id: node.id,
            name: node.name,
            flavor: node.flavor.rawValue,
            subKind: node.subKind?.rawValue,
            isInteresting: node.isInteresting,
            isVisibleInGraph: isVisible,
            parent: node.parent,
            sourceFile: node.sourceFile,
            line: node.location.line,
            referenceCount: refCount,
            referencedBy: inRefs.sorted(),
            references: outRefs.sorted()
        ))

        if topLevelFlavors.contains(node.flavor.rawValue) && node.parent == nil {
            let hasIncoming = !inRefs.isEmpty
            let hasOutgoing = !outRefs.isEmpty
            if !hasIncoming && !hasOutgoing {
                isolatedTypes += 1
                deadCode.append(DeadCodeEntry(
                    id: node.id,
                    name: node.name,
                    flavor: node.flavor.rawValue,
                    sourceFile: node.sourceFile,
                    line: node.location.line,
                    reason: "Isolated type: no incoming or outgoing dependencies",
                    suggestion: "This type is never referenced by other code. Consider removing it or verifying it's used via runtime/reflection."
                ))
            }
        }

        if node.flavor == .variable && node.subKind?.rawValue == "stored" && !node.isInteresting {
            if refCount == 0 {
                deadCode.append(DeadCodeEntry(
                    id: node.id,
                    name: node.name,
                    flavor: node.flavor.rawValue,
                    sourceFile: node.sourceFile,
                    line: node.location.line,
                    reason: "Stored property never read or written with logic",
                    suggestion: "This property is never referenced outside its declaration. It can be safely removed to reduce memory footprint."
                ))
            }

            let onlyFromInit = inRefs.allSatisfy { ref in
                result.nodes.first { $0.id == ref }?.flavor == .initializer
            }
            if refCount > 0 && onlyFromInit && !inRefs.isEmpty {
                initOnlyCount += 1
                deadCode.append(DeadCodeEntry(
                    id: node.id,
                    name: node.name,
                    flavor: node.flavor.rawValue,
                    sourceFile: node.sourceFile,
                    line: node.location.line,
                    reason: "Property only used during init",
                    suggestion: "This variable is only accessed in initializers and never read again. Consider using a local constant instead."
                ))
            }
        }
    }

    let formatter = ISO8601DateFormatter()
    formatter.formatOptions = [.withInternetDateTime]

    let deadCount = deadCode.count
    let total = result.nodes.count
    let pct = total > 0 ? Double(deadCount) / Double(total) * 100 : 0

    return FullSummary(
        version: "1.0",
        generatedAt: formatter.string(from: Date()),
        symbols: symbols,
        deadCode: deadCode,
        pruningStats: PruningStats(
            totalSymbols: total,
            deadSymbols: deadCount,
            isolatedTypes: isolatedTypes,
            writeOnlyProperties: writeOnlyCount,
            initOnlyProperties: initOnlyCount,
            estimatedSavings: String(format: "%.1f%% of symbols are candidates for removal", pct)
        )
    )
}

func collapseModules(result: AnalysisResult, targets: [ParsedTarget]) -> AnalysisResult {
    let mainTargetNames = Set(
        targets
            .filter { $0.type == .executable || $0.type == .unknown }
            .map(\.name)
    )
    let macroTargetNames = Set(
        targets
            .filter { $0.type == .macroTarget }
            .map(\.name)
    )
    let collapsibleTargets = Set(
        targets
            .filter { !mainTargetNames.contains($0.name) }
            .map(\.name)
    )

    var symbolsByTarget: [String: [Node]] = [:]
    for node in result.nodes {
        if let t = node.targetName {
            symbolsByTarget[t, default: []].append(node)
        }
    }

    var moduleNodesList: [ModuleNode] = []
    var collapsedIds: Set<String> = []
    var moduleIdForTarget: [String: String] = [:]

    for targetName in collapsibleTargets {
        let symbols = symbolsByTarget[targetName] ?? []
        guard !symbols.isEmpty else { continue }

        let moduleId = "module:\(targetName)"
        moduleIdForTarget[targetName] = moduleId

        let isMacro = macroTargetNames.contains(targetName)
        let publicCount = symbols.filter { $0.access == .public || $0.access == .open }.count
        let targetType = targets.first { $0.name == targetName }?.type ?? .library

        moduleNodesList.append(ModuleNode(
            id: moduleId,
            name: targetName,
            moduleType: targetType,
            isMacro: isMacro,
            symbolCount: symbols.count,
            publicSymbolCount: publicCount
        ))

        for sym in symbols {
            collapsedIds.insert(sym.id)
        }
    }

    let retainedNodes = result.nodes.filter { !collapsedIds.contains($0.id) }

    var retargetedLinks: [Link] = []
    var seenLinks: Set<String> = []

    for link in result.links {
        let sourceTarget = result.nodes.first { $0.id == link.sourceId }?.targetName
        let targetTarget = result.nodes.first { $0.id == link.targetId }?.targetName

        var newSource = link.sourceId
        var newTarget = link.targetId

        if let st = sourceTarget, let moduleId = moduleIdForTarget[st] {
            newSource = moduleId
        }
        if let tt = targetTarget, let moduleId = moduleIdForTarget[tt] {
            newTarget = moduleId
        }

        if newSource == newTarget { continue }

        let key = "\(newSource)->\(newTarget):\(link.type.rawValue)"
        guard seenLinks.insert(key).inserted else { continue }

        retargetedLinks.append(Link(
            sourceId: newSource,
            targetId: newTarget,
            type: link.type,
            confidence: link.confidence,
            references: link.references
        ))
    }

    let moduleAsNodes = moduleNodesList.map { m in
        Node(
            id: m.id,
            name: m.name,
            flavor: m.isMacro ? .macro : .struct,
            subKind: nil,
            isStatic: false,
            isGlobal: false,
            isNested: false,
            isInteresting: true,
            access: .public,
            parent: nil,
            parentFile: nil,
            sourceFile: "",
            location: SourceLocation(file: "", line: 0, column: 0),
            targetName: m.name,
            memberCount: m.symbolCount
        )
    }

    return AnalysisResult(projectRoot: nil, 
        nodes: retainedNodes + moduleAsNodes,
        links: retargetedLinks,
        resources: result.resources,
        targets: result.targets,
        macros: result.macros,
        moduleNodes: moduleNodesList
    )
}

func extractSummary(from result: AnalysisResult) -> AnalysisResult {
    let summaryFlavors: Set<String> = ["struct", "class", "enum", "actor", "protocol"]
    let summaryNodes = result.nodes.filter { summaryFlavors.contains($0.flavor.rawValue) }
    let summaryIds = Set(summaryNodes.map(\.id))

    let memberCounts = result.nodes.reduce(into: [String: Int]()) { counts, node in
        guard let parent = node.parent, !summaryFlavors.contains(node.flavor.rawValue) else { return }
        counts[parent, default: 0] += 1
    }

    let enrichedNodes = summaryNodes.map { node -> Node in
        Node(
            id: node.id,
            name: node.name,
            flavor: node.flavor,
            subKind: node.subKind,
            isStatic: node.isStatic,
            isGlobal: node.isGlobal,
            isNested: node.isNested,
            isInteresting: node.isInteresting,
            access: node.access,
            parent: node.parent,
            parentFile: node.parentFile,
            sourceFile: node.sourceFile,
            location: node.location,
            targetName: node.targetName,
            memberCount: memberCounts[node.id]
        )
    }

    let summaryLinks = result.links.filter { summaryIds.contains($0.sourceId) && summaryIds.contains($0.targetId) }

    return AnalysisResult(projectRoot: nil, 
        nodes: enrichedNodes,
        links: summaryLinks,
        resources: result.resources,
        targets: result.targets,
        macros: result.macros,
        moduleNodes: result.moduleNodes
    )
}

func extractMembers(of parentId: String, from result: AnalysisResult) -> AnalysisResult {
    let members = result.nodes.filter { $0.parent == parentId }
    let memberIds = Set(members.map(\.id))
    let relevantIds = memberIds.union([parentId])

    let memberLinks = result.links.filter {
        relevantIds.contains($0.sourceId) && relevantIds.contains($0.targetId)
    }

    let parentNode = result.nodes.filter { $0.id == parentId }

    return AnalysisResult(projectRoot: nil, 
        nodes: parentNode + members,
        links: memberLinks,
        resources: [],
        targets: [],
        macros: [],
        moduleNodes: nil
    )
}

func scanFiles(_ filePaths: [String]) -> ([SymbolInfo], [(path: String, tree: SourceFileSyntax)]) {
    var allSymbols: [SymbolInfo] = []
    var fileSources: [(path: String, tree: SourceFileSyntax)] = []
    let totalFiles = filePaths.count
    var processedFiles = 0

    emitProgress(phase: "scanning", processed: 0, total: totalFiles)

    for path in filePaths {
        if shouldSkipFile(path) {
            emitWarning("Skipping excluded file: \(path)")
            processedFiles += 1
            continue
        }

        guard let data = FileManager.default.contents(atPath: path),
              let source = String(data: data, encoding: .utf8) else {
            emitWarning("Skipping unreadable file: \(path)")
            processedFiles += 1
            continue
        }

        let tree: SourceFileSyntax
        do {
            tree = Parser.parse(source: source)
        } catch {
            emitWarning("Skipping unparseable file \(path): \(error)")
            processedFiles += 1
            continue
        }

        fileSources.append((path: path, tree: tree))

        do {
            let collector = SymbolCollector(filePath: path)
            collector.walk(tree)
            allSymbols.append(contentsOf: collector.symbols)
        } catch {
            emitWarning("Symbol collection failed for \(path): \(error)")
        }

        processedFiles += 1
        emitProgress(phase: "scanning", processed: processedFiles, total: totalFiles)
    }

    return (allSymbols, fileSources)
}

func shouldSkipFile(_ path: String) -> Bool {
    let buildIndicators = ["/.build/", "/Build/", "/DerivedData/", "/.swiftpm/", "/checkouts/", "/SourcePackages/", "/.index-build/"]
    for indicator in buildIndicators {
        if path.contains(indicator) { return true }
    }
    let name = (path as NSString).lastPathComponent
    let autoGenSuffixes = ["_generated.swift", ".pb.swift", ".grpc.swift"]
    for suffix in autoGenSuffixes {
        if name.hasSuffix(suffix) { return true }
    }
    return false
}

func scanResources(workspaceRoot: String?) -> [ResourceNode] {
    emitProgress(phase: "resources", processed: 0, total: 1)
    guard let root = workspaceRoot else {
        emitProgress(phase: "resources", processed: 1, total: 1)
        return []
    }
    let scanner = ResourceScanner(workspaceRoot: root)
    let resources = scanner.scan()
    emitProgress(phase: "resources", processed: 1, total: 1)
    return resources
}

func collectSignatures(filePaths: [String], fileSources: [(path: String, tree: SourceFileSyntax)]) -> [String: [SignatureInfo]] {
    var signaturesByFile: [String: [SignatureInfo]] = [:]
    for (path, tree) in fileSources {
        let collector = SignatureCollector(filePath: path)
        collector.walk(tree)
        signaturesByFile[path] = collector.signatures
    }
    return signaturesByFile
}

func safeEncodeToJSON<T: Encodable>(_ value: T, label: String) throws -> String {
    emitProgress(phase: "encoding", processed: 0, total: 1)
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    do {
        let data = try encoder.encode(value)
        guard let json = String(data: data, encoding: .utf8) else {
            throw PrismError.encodingFailed(detail: "\(label): encoded data is not valid UTF-8 (\(data.count) bytes)")
        }
        return json
    } catch let error as PrismError {
        throw error
    } catch {
        throw PrismError.encodingFailed(detail: "\(label): \(error)")
    }
}

func writeOutput(_ json: String, to outputPath: String?) {
    if let outputPath {
        do {
            try json.write(toFile: outputPath, atomically: true, encoding: .utf8)
            fputs("{\"_info\":\"Written to \(outputPath)\"}\n", stderr)
        } catch {
            fputs("{\"_error\":\"Failed to write to \(outputPath): \(error)\"}\n", stderr)
            print(json)
        }
    } else {
        print(json)
    }
}

func emitProgress(phase: String, processed: Int, total: Int) {
    let msg = "{\"_progress\":{\"phase\":\"\(phase)\",\"processed\":\(processed),\"total\":\(total)}}"
    fputs(msg + "\n", stderr)
}

func emitWarning(_ message: String) {
    let escaped = message
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
        .replacingOccurrences(of: "\n", with: "\\n")
    fputs("{\"_warning\":\"\(escaped)\"}\n", stderr)
}

do {
    try run()
} catch let error as PrismError {
    let escaped = error.description
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
        .replacingOccurrences(of: "\n", with: "\\n")
    fputs("{\"_error\":\"\(escaped)\"}\n", stderr)
    exit(1)
} catch {
    let desc = String(describing: error)
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
        .replacingOccurrences(of: "\n", with: "\\n")
    fputs("{\"_error\":\"Unhandled error: \(desc)\"}\n", stderr)
    exit(1)
}
